name: Linting

on:
  pull_request:
    branches_ignore: []

jobs:
  build:
    runs-on: ubuntu-latest

    name: Linting
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Render and Lint
        run:  make lint
